#!/usr/bin/env bash
export PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

if [ "$#" -ne 3 ]; then
    >&2 echo "Illegal number of arguments."
	>&2 echo "Usage: $0 recipient detail1 detail2"
	exit 1
fi

cat <<EOF | mail -s "Message from camsrvd" "$1"
This is camsrvd running on $(hostname -f).

The following camera has been disabled because its command has failed too many times:

$2
$3

You may wish to investigate what is going on. Further information may be available in the Syslog.
EOF

exit 0
